### ISSUE TITLE
There's no test.py?

### ISSUE THREAD

**Issue by BitesizedLion** [Maximellerbach/GamesAutoPilot#1]
The README.md file says to run test.py, but that does not exist?

**Comment by BitesizedLion** [comment]
I found that it was renamed to main.py, running that however I get a new issue...
`Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from custom_modules import architectures
ModuleNotFoundError: No module named 'custom_modules'`

**Comment by BitesizedLion** [comment]
Fixed that issue, now onto another...

`Traceback (most recent call last):
  File "C:\Users\Casper\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\Casper\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Casper\Documents\GitHub\GamesAutoPilot\udpReceiver.py", line 69, in listen
    data, addr = self.sock.recvfrom(self.FH4BufSize)
socket.timeout: timed out
`
